version: '3'

services:
  server:
      restart: always
      container_name: spring
      build: ./server
      working_dir: /server
      volumes:
        - ./server:/server
        - ~/.m2:/root/.m2
      ports:
        - 9090:9090
      command: mvn clean spring-boot:run